import { Metadata } from "next";
import { getDictionary } from "../dictionaries";
import { PageProps } from "../interview/questions/page";

export const metadata: Metadata = {
    title: "Interview with Ai",
    description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: { children: React.ReactNode, params: Promise<PageProps['params']> }) {
    const { locale } = await params;
    const disc = await getDictionary(locale);
    return (
        <div className="col-span-2 flex flex-col mt-auto mb-auto w-fit mx-auto p-8 border rounded-2xl shadow h-fit">
            <h1 className="text-2xl font-bold mb-6">{disc.interviewLayout}</h1>
            {children}
        </div>
    );
}
