import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession, Session } from "next-auth";
import NavMenu from "@/components/NavMenu";
import { authOptions } from "@/lib/authOptions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Interview with Ai",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: 'en | tr | fr | de | hi | zh' }>
}>) {
  const { lang } = await params;
  const session: Session | null = await getServerSession(authOptions);
  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavMenu user={session} />
        <main className="lg:mt-15 items-center justify-center flex flex-col">
          {children}
        </main>
      </body>
    </html>
  );
}
