import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession, Session } from "next-auth";
import NavMenu from "@/components/NavMenu";
import { authOptions } from "@/lib/authOptions";
import { cookies } from "next/headers";
import { PageProps } from "./interview/questions/page";
import { getDictionary } from "./dictionaries";
import { langProps } from "@/components/blocks/StartButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Interview with Ai",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<PageProps['params']>;
}>) {
  const { locale } = await params;
  const session = await getServerSession(authOptions);
  const disc: langProps = await getDictionary(locale)
  return (
    <html lang={locale} className='dark'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <NavMenu session={session} localeData={disc} />
        <main className="lg:mt-10 lg:mx-5">
          {children}
        </main>

        <footer className="border-t py-6 text-start px-2 text-sm text-muted-foreground mt-12">
          <p>© 2025 Kerem Tanrıverdi. All rights reserved.</p>

        </footer>
      </body>
    </html>
  );
}
