import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession, Session } from "next-auth";
import NavMenu from "@/components/NavMenu";
import { authOptions } from "@/lib/authOptions";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Interview with Ai",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: 'en | tr | fr | de | hi | zh' }>
}>) {
  const { lang } = await params;
  const session: Session | null = await getServerSession(authOptions);
  const cookieStore = cookies()
  const theme = (await cookieStore).get("theme")?.value || "light"
  return (
    <html lang={lang} className='dark'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavMenu user={session} />
        <main className="lg:mt-10 lg:mx-5">
          {children}
        </main>

        <footer className="border-t py-6 text-end px-2 text-sm text-muted-foreground mt-12">
          <p>© 2025 Kerem Tanrıverdi. All rights reserved.</p>

        </footer>
      </body>
    </html>
  );
}
